protected/models/Fuelstations.php
<?php

/**
 * This is the model class for table "{{fuelstations}}".
 *
 * The followings are the available columns in table '{{fuelstations}}':
 * @property integer $id
 * @property string $name
 * @property string $address
 * @property integer $active
 */
class Fuelstations extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Fuelstations the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{fuelstations}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name, address', 'required'),
			array('id, active', 'numerical', 'integerOnly'=>true),
			array('name, address, latitude, longitude', 'length', 'max'=>127),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, name, address, active, latitude, longitude', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'address' => 'Address',
			'active' => 'Active',
			'latitude'=>'Latitude',
			'longitude'=>'Longitude',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('name',$this->name,true);
		$criteria->compare('address',$this->address,true);
		$criteria->compare('active',$this->active);
		$criteria->compare('latitude',$this->latitude);
		$criteria->compare('longitude',$this->longitude);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'pagination'=>array(
				'pageSize'=>40,
			),
		));
	}
}

protected/controllers/FuelstationsController.php
<?php

class FuelstationsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('@'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','excel','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				//'users'=>array('admin'),
				'expression'=>'Yii::app()->user->isAdmin()',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Fuelstations;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Fuelstations']))
		{			
			$model->attributes=$_POST['Fuelstations'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Fuelstations']))
		{
			$model->attributes=$_POST['Fuelstations'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		//throw new CHttpException(400,'Delete operation is stopped.');
        //return;

        if(Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax']))
                $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
        }
        else
            throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		/*$dataProvider=new CActiveDataProvider('Fuelstations');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));*/
		
		$model=new Fuelstations('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Fuelstations']))
			$model->attributes=$_GET['Fuelstations'];

		$this->render('index',array(
			'model'=>$model,
			'dataProvider'=>$model->search(),
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Fuelstations('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Fuelstations']))
			$model->attributes=$_GET['Fuelstations'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer the ID of the model to be loaded
	 */
	public function loadModel($id)
	{
		$model=Fuelstations::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='fuelstations-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	
        public function actionExcel()
    {
        $model=new Fuelstations('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['criteria']))
            $model->attributes=$_GET['criteria'];
        
        $this->widget('ext.phpexcel.EExcelView', array(
            'dataProvider'=> $model->search(),
            'title'=>'iFleet_Fuelstations',
            //'autoWidth'=>true,
            'grid_mode'=>'export',
            'exportType'=>'Excel2007',
            'filename'=>'iFleet_Fuelstations',

                'columns'=>array(
                
                'id',
       array(
            'name' => 'name',
            'type'=>'raw',
            'value' => 'CHtml::link(CHtml::encode($data->name),array("view","id"=>$data->id))',
        ),
       'address',
    ),
            
        ));
        Yii::app()->end();
    }
    
    
    
    
	
}

protected/views/fuelstations/_form.php
<?php
/* @var $this FuelstationsController */
/* @var $model Fuelstations */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'fuelstations-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<!--div class="row">
		<?php echo $form->labelEx($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
		<?php echo $form->error($model,'id'); ?>
	</div-->

	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>127)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'address'); ?>
		<?php echo $form->textField($model,'address',array('size'=>60,'maxlength'=>127)); ?>
		<?php echo $form->error($model,'address'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'latitude'); ?>
		<?php echo $form->textField($model,'latitude',array('size'=>60,'maxlength'=>127)); ?>
		<?php echo $form->error($model,'latitude'); ?>
	</div>
	<div class="row">
		<?php echo $form->labelEx($model,'longitude'); ?>
		<?php echo $form->textField($model,'longitude',array('size'=>60,'maxlength'=>127)); ?>
		<?php echo $form->error($model,'longitude'); ?>
	</div>

	<!--div class="row">
		<?php echo $form->labelEx($model,'active'); ?>
		<?php echo $form->textField($model,'active'); ?>
		<?php echo $form->error($model,'active'); ?>
	</div-->

	<!--div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div-->
	
	<div class="clearfix"></div>
	
	<div align="left">
    <?php $this->widget('bootstrap.widgets.TbButton',array(
        'label' => 'Save',
        'type' => 'primary',
        'buttonType'=>'submit', 
        'size' => 'medium'
        ));
    ?>
    </div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/fuelstations/_search.php
<?php
/* @var $this FuelstationsController */
/* @var $model Fuelstations */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<!--<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>-->
	<div class="fl">
		<div class="row">
			<?php echo $form->label($model,'name'); ?><br />
			<?php echo $form->textField($model,'name',array('maxlength'=>127)); ?>
		</div>
	</div>
	<div class="fl">
		<div class="row">
			<?php echo $form->label($model,'address'); ?><br />
			<?php echo $form->textField($model,'address',array('maxlength'=>127)); ?>
		</div>
	</div>
	<!--<div class="row">
		<?php echo $form->label($model,'active'); ?>
		<?php echo $form->textField($model,'active'); ?>
	</div>-->

	<div class="row buttons" align="right">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/fuelstations/_view.php
<?php
/* @var $this FuelstationsController */
/* @var $data Fuelstations */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('address')); ?>:</b>
	<?php echo CHtml::encode($data->address); ?>
	<br />

	<!--<b><?php echo CHtml::encode($data->getAttributeLabel('active')); ?>:</b>
	<?php echo CHtml::encode($data->active); ?>
	<br />-->


</div>

protected/views/fuelstations/admin.php
<?php
/* @var $this FuelstationsController */
/* @var $model Fuelstations */

$this->breadcrumbs=array(
	'Fuel Stations'=>array('index'),
	'Manage',
);
if(!Yii::app()->user->isViewUser()) {
    $this->menu=array(
    	array('label'=>'Fuel Stations List ', 'url'=>array('index')),
    	array('label'=>'New Fuel Station', 'url'=>array('create')),
    );
}

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('fuelstations-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h4>Manage Fuel Stations</h4>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
    'id'=>'fuelstations-grid',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'columns'=>array(
        'id',
        'name',
        'address',
        'active',
        array(
            'class'=>'CButtonColumn',
            'template'=>'{view}{update}{delete}',
            'buttons'=>array
            (
                'view' => array
                (
                    'url'=>'$this->grid->controller->createUrl("/fuelstations/view", array("id"=>$data->primaryKey))',
                ),
                'update' => array
                (
                    'url'=>'$this->grid->controller->createUrl("/fuelstations/update", array("id"=>$data->primaryKey))',
                ),
                'delete' => array
                (
                    'url'=>'$this->grid->controller->createUrl("/fuelstations/delete", array("id"=>$data->primaryKey))',
                ),
            ),
        ),
    ),
)); ?>

<?php /*$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'fuelstations-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'address',
		'active',
		array(
			'class'=>'CButtonColumn',
		),
	),
));*/ ?>

protected/views/fuelstations/create.php
<?php
/* @var $this FuelstationsController */
/* @var $model Fuelstations */

$this->breadcrumbs=array(
	'Fuel Stations'=>array('index'),
	'Create',
);
if(!Yii::app()->user->isViewUser()) {
	$this->menu=array(
		array('label'=>'Fuel Stations List', 'url'=>array('index')),
		array('label'=>'Manage Fuel Stations', 'url'=>array('admin')),
	);
}
?>

<h4>New Fuel Station</h4>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/fuelstations/index.php
<?php
/* @var $this FuelstationsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Fuel Stations',
);
if(!Yii::app()->user->isViewUser()) {
	$this->menu=array(
		array('label'=>'New Fuel Station', 'url'=>array('create')),
		array('label'=>'Manage Fuel Stations', 'url'=>array('admin')),
	);
}
?>

<h4>Fuel Stations</h4>

<?php /*$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
));*/ ?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'fuelstations-grid',
	'dataProvider'=>$dataProvider,
    'filter'=>$model,
	'columns'=>array(
		'id',
        array(
            'name' => 'name',
            'type'=>'raw',
            'value' => 'CHtml::link(CHtml::encode($data->name),array("view","id"=>$data->id))',
        ),
		'address',
		'latitude',
		'longitude',
	),
)); 

$this->widget('application.extensions.print.printWidget', array(
    //'coverElement' => '.container', //main page which should not be seen
    'cssFile' => '/fleet/themes/shadow_dancer/images/css/print.css',
    'printedElement' => '#fuelstations-grid', //element to be printed
    'title' => CHtml::image("/fleet/themes/shadow_dancer/images/logo1.png"),
	  'title' => 'Transport Department - Fuel Stations List',
));
?>
<?php
    echo CHtml::normalizeUrl(CHtml::link('Export to Excel',array('excel','criteria'=>$_GET['Fuelstations'])));
?> &nbsp; &nbsp; &nbsp;

protected/views/fuelstations/update.php
<?php
/* @var $this FuelstationsController */
/* @var $model Fuelstations */

$this->breadcrumbs=array(
	'Fuel Stations'=>array('index'),
	$model->name=>array('view','id'=>$model->id),
	'Update',
);
if(!Yii::app()->user->isViewUser()) {
	$this->menu=array(
		array('label'=>'Fuel Stations List', 'url'=>array('index')),
		array('label'=>'New Fuel Station', 'url'=>array('create')),
		array('label'=>'View Fuel Station', 'url'=>array('view', 'id'=>$model->id)),
		array('label'=>'Manage Fuel Stations', 'url'=>array('admin')),
	);
}
?>

<h4>Update Fuel Station : <?php echo $model->id; ?></h4>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/fuelstations/view.php
<?php
/* @var $this FuelstationsController */
/* @var $model Fuelstations */

$this->breadcrumbs=array(
	'Fuel Stations'=>array('index'),
	$model->name,
);
if(!Yii::app()->user->isViewUser()) {
	$this->menu=array(
		array('label'=>'Fuel Stations List', 'url'=>array('index')),
		array('label'=>'New Fuel Station', 'url'=>array('create')),
		array('label'=>'Update Fuel Station', 'url'=>array('update', 'id'=>$model->id)),
		//array('label'=>'Delete Fuelstation', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?','csrf' => true)),
		array('label'=>'Manage Fuel Stations', 'url'=>array('admin')),
	);
}
?>

<h4>View Fuel Station : <?php echo $model->id; ?></h4>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'address',
		'latitude',
		'longitude',
		//'active',
	),
)); ?>